wandb:
  project: "report_generation_validation_dinov2_backbone_standard_decoder"

model:
  class_name: "amber_cls"
  runs: ["out/8ndib7nm/ckpt.pt", "out/f6rrk6ph/ckpt.pt", "out/zvfc6z3j/ckpt.pt"]
  name: "Amber CLS baseline on cesm"
  norm_mean: [ 0.485, 0.456, 0.406 ]
  norm_std: [ 0.229, 0.224, 0.225 ]

test_data:
  imgs_shape: [ 512, 512 ]
  img_resize: 560
  imgs_path: "../data/report_generation_split/cesm-rg-test.bin"
  csv_path: "../data/report_generation_split/cesm-rg-test.csv"
  grayscale_channel: False

trainer:
  batch_size: 2048
  bootstrap_iters: 2000
  accelerator: "gpu"
  precision: "bfloat16"
